# Genel Ayarlar
target: "eximbank.gov.tr"  # veya IP adresi
scan_type: "full"  # quick, standard, full
output_format: "html"  # html, pdf, json

# NMAP Ayarları
nmap:
  options: "-sV -sC -O --script=vulners"
  timing: "-T4"
  ports: "--top-ports 1000"
  custom_scripts: "config/nmap_scripts/"

# Nuclei Ayarları
nuclei:
  templates: "config/nuclei-templates"
  severity: "medium,high,critical"
  rate_limit: 100
  timeout: 5

# OWASP ZAP Ayarları
zap:
  api_key: "change-me-123"
  proxy: "http://localhost:8080"
  context: "default"
  policy: "Default Policy"
  ajax_spider: true
  active_scan: true
